### ISSUE TITLE
Post Code

### ISSUE THREAD

**Issue by dfense** [njfaria/dalylog#1]
I really like the idea of pushing the daly BMS data over MQTT topic. 
Are you going to post code for this ? 
Are the screenshots of existing software posted somewhere else ? 

Hopeful the community can get access to this. Really gives a lot of 'connected' options for the Daly BMS product(s)

**Comment by njfaria** [comment]
Software for raspberry is online under releases.
https://github.com/njfaria/dalylog/releases/tag/0.9.0
Just use ypur raspberry desktop..

A sexta, 23/10/2020, 16:23, dfense <notifications@github.com> escreveu:

**Comment by dfense** [comment]
A bit confused, as all I see checked into the 0.9.0 tag branch (or any) are

- 2 PNG files
- 1 README.md
- 1 dummy.txt 
<no program or scripting code anywhere>

Am i missing something?
I downloaded the *.tar.gz and the *.zip plus browse the git online.

**Comment by njfaria** [comment]
check the link above.. its a release, there is no source code.
its a zip file, which you unzip on your raspberry.
