### ISSUE TITLE
Dual BMS Daly

### ISSUE THREAD

**Issue by dprinzi** [njfaria/dalylog#16]
Hello, how can I use 2 BMS Daly? i tried to duplicate the folder which contains dalylog on raspberry and connected a different interface. However, sending data to emoncms uses the same prefixes as the first dalylog (emon/daly) and conflicts with sent data sent by both. It should send with different prefixes like "emon/daly2" but it is not editable. Anyone know how to do it?

**Comment by dprinzi** [comment]
found the solution. thank you

**Comment by Pinky-bit** [comment]
Hi, I also have the same problem. Could you tell me how you solved it? Thank you

**Comment by kxn25** [comment]
I also would like ti know how to use Daly log with a second Battery Pack?
