### ISSUE TITLE
MQTT solpiplog/daly/temp1 not send?

### ISSUE THREAD

**Issue by SunnyPerth** [njfaria/dalylog#7]
Hi Team, 

running the latest version (1.0.0) of this fine piece of software, have been running it for the past few weeks and it works like a dream. Love to get the real data from the Daly into my various dashboards. 

However it seems that the tool doesn't send the /daly/temp1 mqtt topic? Is that correct? 

Cheers,
Yuri

**Comment by danielforster** [comment]
Nuno,

I just noticed that the battery temp sensor is not in the MQTT package sent too. Can you see if you can sort this?

Many thanks as always,

Daniel

**Comment by njfaria** [comment]
Yes some user mentioned that. A bug that i implemented. Do i have access to
the raspberry ? I dont have a daly...

A quarta, 16/06/2021, 15:56, danielforster ***@***.***>
escreveu:

**Comment by danielforster** [comment]
Nuno,

Yes, I have 4x separate 5.5kw battery packs with a pi4/BMS in each pack. They all report to MQTT as pack1/ pack2/ pack3/ and pack4/.

I can SSH into each pi or use VNC to see each pi's desktop.

Take care,

Daniel

**Comment by SunnyPerth** [comment]
Hi Nuno, 

Any luck with this? If you don't have access to a Pi and Daly, I do (and so does Daniel I think).  
As the application on the pi does show the temperature, I know that your app does have the data. 
So, I think it's as simple that your MQTT routine doesn't send the data, it probably just misses the line? 

As you do not share the source code, I can't check / help. But I'm happy top help troubleshoot and test. 
Let me know if you can share the source code, or a version that you have fixed and I can test before we publish it? 
Happy for you to send me a pm to solve. 

cheers,
Yuri

**Comment by njfaria** [comment]
@SunnyPerth @danielforster version 1.0.1 out. temperature sending solved.

**Comment by SunnyPerth** [comment]
Super Thanks Team!

**Comment by SunnyPerth** [comment]
Hey Team, I've installed the new version, and now get the temp - great. 
However I'm now seeing an odd behaviour that I can't explain in home assistant, see also image attached. Just wondering if others see this or have seen this, and since the only thing I've changed is the Daly software if this is related due to the upgrade. 
So what I see is that opening sensor data detail graph that I get via the Daly BMS, the line chart is now coloured in above/under a (to me) value. 
See the SOC and remaining ah examples. ![image](https://user-images.githubusercontent.com/84317841/132023293-f3406883-cacb-484b-9a50-321c9a77e7d7.jpeg)![image](https://user-images.githubusercontent.com/84317841/132023305-e69b5b87-5457-4757-9efd-69993fa53ed7.jpeg)

I've not (yet) reverted to the old version to see if it's due to the new version - will do in next days, but wondering if anyone else has seen this ? 

Cheers

**Comment by njfaria** [comment]
How did it looked before ?
I dont have a daly, therefore i am relying on your testing.

**Comment by SunnyPerth** [comment]
Thx mate, appreciate you looking into this. This is how a graph should look like. ![image](https://user-images.githubusercontent.com/84317841/132072077-1782f841-436e-4cfe-9799-959b67a589b9.jpeg)

It's almost like the app is sending a constant value and then the real value - I'll have a quick look this morning to see if that's the case & if this behaviour stops when switch back to previous version.

**Comment by SunnyPerth** [comment]
Hi mate - just checked. The latest version of the app 1.0.1 does send mqtt values alternating, the (wrong) initial value and the real value, followed by the wrong and then real value.. this results in the graph looking likes it's filled in, but if you would zoom in you see both values. 
It also does send the data that every second ( it every minute ). 
I've reverted to previous version which solved the problem, but didn't/doesn't show the temp ;)

**Comment by njfaria** [comment]
For some reason do you got two versions of dalylog logging ?
I am trying to get some feedback from other users.

**Comment by SunnyPerth** [comment]
I had to reinstall some things on the Pi, and spend some more time on DalyLog - it now works as it should. Temperature is being send, and SoC is good as well. As well with all other measurements). 
So - likely you were correct and something wrong at my end when I had that problem. Think we can close out this one! (I will do). Thanks!
